### ISSUE TITLE
No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'

### ISSUE THREAD

**Issue by kodeo** [jimbobbennett/MvvmCross-VisualStudioAddIn#5]
I'm getting the following two errors on compiling a new solution created with this plugin:

> Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.	App1.Droid	c:\dev\App1\App1\App1.Droid\obj\Debug\__library_projects__\Xamarin.Android.Support.v7.AppCompat\library_project_imports\res\values-v24\values-v24.xml

> Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.	App1.Droid	c:\dev\App1\App1\App1.Droid\obj\Debug\__library_projects__\Xamarin.Android.Support.v7.AppCompat\library_project_imports\res\values-v24\values-v24.xml	

I was originally getting this in Visual Studio 2015. I've tried installing completely fresh copy of Windows with Visual Studio 2017 Community, and the same thing is happening.

**Comment by jimbobbennett** [comment]
What Android SDK version do you have installed? You'll need SDK 7.1 (API 25) installed for this to work, and unfortunately there is no way to limit a template based on an Android SDK version.

**Comment by kodeo** [comment]
I only had up to API 23 installed, which is the latest Visual Studio comes with.  Installing API 25 does fix it though, thanks. The project also continues to build correctly after I remove API 25 again, for some reason.

**Comment by jimbobbennett** [comment]
Cool - glad it works with API 25. I've updated the marketplace description to mention this is needed.
