### ISSUE TITLE
Fails to install on Mac

### ISSUE THREAD

**Issue by seank-com** [jimbobbennett/MvvmCross-VisualStudioAddIn#6]
1. Install Visual Studio Community on clean Mac
2. Launch Visual Studio for Mac
3. Goto Visual Studio Community | Extensions...
4. Click Gallery tab and enter Mvvmcross in search box
5. select MvvmCross Template pack
6. Press Install
<img width="428" alt="screen shot 2017-07-19 at 1 12 56 pm" src="https://user-images.githubusercontent.com/1326518/28387573-7c5ceae4-6c84-11e7-9222-cfda1911aa96.png">

The files referenced as missing are both there

```
-rwxr-xr-x  1 seank  admin    14 Jul 19 13:02 StylesheetTemplate.css*
...
-rw-r--r--  1 seank  admin   606 Jul 19 13:02 RazorTagHelper.xft.xml
```

I initially tried to install Visual Studio from brew, I'm going to wipe my machine and see if that is the issue.

**Comment by jimbobbennett** [comment]
Wrong GitHub repo (this is the VS for Windows one).
Also the error is from another extension. It's a weird quirk when you install an extension it reports any errors in all extension you've tried to install. This is an error in an Asp.Net extension.

**Comment by seank-com** [comment]
Are there extensions automatically installed with Visual Studio? I did not install any other extensions.

**Comment by jimbobbennett** [comment]
Web support is an extension included with VS for Mac, so no idea why it is broken. Try re-installing VS for Mac?

**Comment by seank-com** [comment]
Just did. 

1. Option-Command-R
2. Erase Disk with DiskUtil
3. Install Sierra
4. Install Xcode
5. Install Visual Studio
6. Add MvvmCross extension

same error

I don't need Asp.net so I'll see if I can figure out how to uninstall that.

**Comment by seank-com** [comment]
There is no way to fix this from the UI, that I can find. If you go to a terminal console and run the following
```
open /Applications/Visual\ Studio.app/Contents/Resources/lib/monodevelop/AddIns
```

Then move the AspNet folder and these three files from the MonoDevelop.Debugger.Soft folder
```
MonoDevelop.Debugger.Soft.AspNet.dll
MonoDevelop.Debugger.Soft.AspNet.pdb
MonoDevelop.Debugger.Soft.AspNet.xml
```
to a location outside the application (Desktop) then restart VS, the error will no longer happen.

That said, even though you get the error, the extension appears to work once you get over the significant hurdles configuring and updating the SDKs, packages and project settings.

**Comment by jimbobbennett** [comment]
As mentioned, the error is nothing to do wit my extension - you'd get the same from installing any other extension.

The SDK is the nature of Android development. I can't update the SDK from an extension but I can improve the documentation - I've created a ticket for this.

What problems are you having with packages and project settings?

**Comment by jimbobbennett** [comment]
It might be worth going to help->report a problem in VS for Mac and sending them the error you are seeing.

**Comment by seank-com** [comment]
I'm not sure I can remember it all but I think I had to do the following

I had to go to the SDK Manager and check and apply the following platform components
- Android 7.1 Nougat
  - Android SDK Platform 25
  - Google APIs Intel x86 Atom System Image
  - Google APIs ARM EABi v7a System Image
- Android 6.0 - Marshmallow
  - Android SDK Platform 23
  - Intel x86 Atom System Image
  - Google APIs Intel x86 Atom System Image
  - Google APIs
  - Google APIs

Then I had to add the Xamarin.Android.Support.v7.AppCompat Package to my .Droid project

Then go into the options for my .Core project and change
- General / .NET Portable to PCL 4.5 - Profile259

Then go into the options for my .Droid project and change
-  General / Target framework to Android 7.1 (Nougat)
- Android Application / Minimum Android version to Override - Android 6.0 (API level 23)
- Android Application / Target Android version to Automatic - use target framework versions (API 25)
